/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.editor;

import Handlers.JPEGHandler;
import ListasEnlazadas.ImagenP;
import ListasEnlazadas.ListaImagen;
import com.cambioColor.AzulImagen;
import com.cambioColor.CambiarColor;
import static com.cambioColor.CambiarColor.bmp;
import com.cambioColor.BlancoNegro;
import com.menu.menu;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.cambioColor.BlancoNegro;
import com.cambioColor.CambiarColorAzul;
import com.cambioColor.Hrotacion;
import com.cambioColor.RGBimagen;
import com.cambioColor.SepiaImagen;
import com.cambioColor.VerdeImagen;
import com.cambioColor.Vrotacion;
import com.cambioColor.bmpajpg;
import com.cambioColor.copiaImg;
import com.cambioColor.jpgabmp;
import java.net.URL;

/**
 *
 * @author PERSONAL
 */
public class editor extends javax.swing.JFrame{
    ListaImagen li;
    String foto;
    public String format;
    public static String nombreImg;
    public String rutaImagen;
    public JFileChooser jFileChooser = new JFileChooser();
    public editor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnjpgabmp = new javax.swing.JRadioButton();
        btncopia = new javax.swing.JRadioButton();
        btnrgb = new javax.swing.JRadioButton();
        btnModificar = new javax.swing.JRadioButton();
        btnBN = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btnEjecutar = new javax.swing.JPanel();
        lblEjecutar = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JPanel();
        lblAgregar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Editor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 40));

        btnjpgabmp.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnjpgabmp.setText("JPEG a BMP y viceversa ");
        btnjpgabmp.setBorderPainted(true);
        jPanel1.add(btnjpgabmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        btncopia.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btncopia.setText("Copia – JPEG");
        btncopia.setBorderPainted(true);
        jPanel1.add(btncopia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        btnrgb.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnrgb.setText("Rojo - Verde - Azul - Sepia ");
        btnrgb.setBorderPainted(true);
        jPanel1.add(btnrgb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        btnModificar.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnModificar.setText("Modificar Imagen");
        btnModificar.setBorderPainted(true);
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        btnBN.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnBN.setText("Blanco y Negro");
        btnBN.setBorderPainted(true);
        btnBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBNActionPerformed(evt);
            }
        });
        jPanel1.add(btnBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 190, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 190, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 190, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 190, 10));

        btnEjecutar.setBackground(new java.awt.Color(193, 204, 204));

        lblEjecutar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEjecutar.setForeground(new java.awt.Color(51, 51, 51));
        lblEjecutar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEjecutar.setText("Ejecutar");
        lblEjecutar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEjecutar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEjecutarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEjecutarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEjecutarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEjecutarLayout = new javax.swing.GroupLayout(btnEjecutar);
        btnEjecutar.setLayout(btnEjecutarLayout);
        btnEjecutarLayout.setHorizontalGroup(
            btnEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEjecutar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnEjecutarLayout.setVerticalGroup(
            btnEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEjecutar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnEjecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 130, 40));

        btnAgregar.setBackground(new java.awt.Color(193, 204, 204));

        lblAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(51, 51, 51));
        lblAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregar.setText("Agregar Imagen");
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAgregarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAgregarLayout = new javax.swing.GroupLayout(btnAgregar);
        btnAgregar.setLayout(btnAgregarLayout);
        btnAgregarLayout.setHorizontalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnAgregarLayout.setVerticalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 140, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 160, 140));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblEjecutarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEjecutarMouseEntered
        btnEjecutar.setBackground(Color.gray);
    }//GEN-LAST:event_lblEjecutarMouseEntered

    private void lblEjecutarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEjecutarMouseExited
        btnEjecutar.setBackground(new Color(193,204,204));
    }//GEN-LAST:event_lblEjecutarMouseExited

    private void lblAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseEntered
        btnAgregar.setBackground(Color.gray);
    }//GEN-LAST:event_lblAgregarMouseEntered

    private void lblAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseExited
        btnAgregar.setBackground(new Color(193,204,204));
    }//GEN-LAST:event_lblAgregarMouseExited

    private void lblEjecutarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEjecutarMouseClicked
        /*if (btnBN.isSelected()) {
            System.out.println(rutaImagen);
            File carpeta = new File("patoPrueba");
            if (!carpeta.exists()) {
                carpeta.mkdirs();
            }

            // Guardar la imagen del label en un archivo
            if (lblImagen.getIcon() != null) {
                try {
                    // Obtener la imagen del icono del label y convertirla a BufferedImage
                    ImageIcon icono = (ImageIcon) lblImagen.getIcon();
                    Image imagen = icono.getImage();
                    BufferedImage bufferedImagen = new BufferedImage(imagen.getWidth(null), imagen.getHeight(null), BufferedImage.TYPE_INT_RGB);
                    Graphics2D g = bufferedImagen.createGraphics();
                    g.drawImage(imagen, 0, 0, null);
                    g.dispose();

                    // Convertir la imagen a escala de grises
                    BufferedImage blancoNegro = new BufferedImage(bufferedImagen.getWidth(), bufferedImagen.getHeight(), BufferedImage.TYPE_BYTE_GRAY);
                    Graphics2D g2 = blancoNegro.createGraphics();
                    g2.drawImage(bufferedImagen, 0, 0, null);
                    g2.dispose();
                    System.out.println(blancoNegro);

                    // Guardar la imagen en escala de grises en un archivo
                    String nombreArchivo = "CambiarColor.jpg";
                    File archivoSalida = new File("patoPrueba", nombreArchivo);
                    System.out.println(archivoSalida);
                    ImageIO.write(blancoNegro, "jpg", archivoSalida);
                    JOptionPane.showMessageDialog(null, "Imagen generada correctamente");

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se selccionó ninguna imagen");
            }
        }*/
        File carpeta = new File("Imagen");
            if (!carpeta.exists()) {
                carpeta.mkdirs();
            }
        if (btnBN.isSelected()) {           

            System.out.println("Ingreso ");
            BlancoNegro bn = new BlancoNegro(foto);
            try {
                JPEGHandler.runHandler(bn);
            } catch (Exception e) {
            }
            JOptionPane.showMessageDialog(null, "Imagen generada correctamente");

        }
        if (btncopia.isSelected()) {
            copiaImg copia = new copiaImg(foto);
            try {
                JPEGHandler.runHandler(copia);
            } catch (Exception e) {
            }
            JOptionPane.showMessageDialog(null, "Copia generada correctamente");
        }
        if (btnjpgabmp.isSelected()) {
            
            /*try {
                URL url = new URL(foto);
                BufferedImage image = ImageIO.read(url);
                ImageIO.write(image, "bmp", new File("C:\\Users\\PERSONAL\\OneDrive\\Desktop\\IPC1_S12023_Proyecto2_202206560\\Imagen\\"+parts[0]+".bmp"));
            } catch (Exception e) {
            }*/
            if(format.equals("jpg")){
                jpgabmp formato = new jpgabmp(foto);
                try {
                    JPEGHandler.runHandler(formato);
                } catch (Exception e) {
                }
            }else if(format.equals("bmp")){
                bmpajpg formato1 = new bmpajpg(foto);
                try {
                    JPEGHandler.runHandler(formato1);
                } catch (Exception e) {
                }
            }
            
            JOptionPane.showMessageDialog(null, "Cambio generado correctamente");
        } 
        if (btnrgb.isSelected()) {           

            System.out.println("Ingreso ");
            RGBimagen rgbi = new RGBimagen(foto);
            try {
                JPEGHandler.runHandler(rgbi);
            } catch (Exception e) {
            }
            AzulImagen rgbi2 = new AzulImagen(foto);
            try {
                JPEGHandler.runHandler(rgbi2);
            } catch (Exception e) {
            }
            VerdeImagen rgbi3 = new VerdeImagen(foto);
            try {
                JPEGHandler.runHandler(rgbi3);
            } catch (Exception e) {
            }
            SepiaImagen rgbi4 = new SepiaImagen(foto);
            try {
                JPEGHandler.runHandler(rgbi4);
            } catch (Exception e) {
            }
            JOptionPane.showMessageDialog(null, "Imagenes RGB y Sepia generadas correctamente");

        } if (btnModificar.isSelected()) {
            Hrotacion rotacion = new Hrotacion(foto);
            try {
                JPEGHandler.runHandler(rotacion);
            } catch (Exception e) {
            }
            Vrotacion rotacion2 = new Vrotacion(foto);
            try {
                JPEGHandler.runHandler(rotacion2);
            } catch (Exception e) {
            }
            JOptionPane.showMessageDialog(null, "Rotación Horizontal y Vertical generada correctamente");
        }else {
            JOptionPane.showMessageDialog(null, "No se selccionó ninguna categoria");
        }


    }

    //Método para eliminar la carpeta "patoPrueba" al cerrar el programa
    private void eliminarCarpetaAlSalir() {
        File carpeta = new File("Imagen");
        if (carpeta.exists()) {
            File[] archivos = carpeta.listFiles();
            for (File archivo : archivos) {
                archivo.delete();
            }
            carpeta.delete();
        }

    }//GEN-LAST:event_lblEjecutarMouseClicked

    private void lblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseClicked
        agregarImageALista();
        /*FileNameExtensionFilter filtrado = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        jFileChooser.setFileFilter(filtrado);
        

        int respuesta = jFileChooser.showOpenDialog(this);

        if (respuesta == JFileChooser.APPROVE_OPTION) {
            rutaImagen = jFileChooser.getSelectedFile().getPath();
            Image mImagen = new ImageIcon(rutaImagen).getImage();
            ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH));
            lblImagen.setIcon(mIcono);
            System.out.println("Hola");
        }*/
        
    }//GEN-LAST:event_lblAgregarMouseClicked

    private void agregarImageALista(){
        ImagenP actual = buscarImagen();
        foto = actual.getPath_();
        
        String[] parts = actual.getName().split("\\.");
        nombreImg = parts[0];
        format = parts[1];
        System.out.println(foto);
        System.out.println(actual.toString());
        if(!foto.equals(""))
        {
            
            mostrarImagen(this.lblImagen, foto);
            System.out.println(actual);
            
        }
        
    }
    

    /**/
    private ImagenP buscarImagen(){
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("jpg, jpeg, png, bmp", "jpg", "jpeg", "png", "bmp");
        fc.setFileFilter(filtro);
        
        int resp = fc.showOpenDialog(this);
        if(resp==JFileChooser.APPROVE_OPTION){
            String nombre = fc.getSelectedFile().getName();
            String ubicacion = fc.getSelectedFile().getPath();
            System.out.println(nombre + " "+ ubicacion);
            return new ImagenP(nombre, ubicacion);
        }
        return null;
    }
    
    private void mostrarImagen(JLabel cuadro, String ruta){
    
        if(!ruta.equals("")){
            Image img = new ImageIcon(ruta).getImage();
            img = img.getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imgI = new ImageIcon(img);
            cuadro.setIcon(imgI);
        }
    }
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        menu form1 = new menu();
        this.dispose();
        form1.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAgregar;
    private javax.swing.JRadioButton btnBN;
    private javax.swing.JPanel btnEjecutar;
    private javax.swing.JRadioButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JRadioButton btncopia;
    private javax.swing.JRadioButton btnjpgabmp;
    private javax.swing.JRadioButton btnrgb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblEjecutar;
    private javax.swing.JLabel lblImagen;
    // End of variables declaration//GEN-END:variables
}
