/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.menu;

import com.biblioteca.Biblioteca;
import com.convertidor.convertidor;
import com.editor.editor;
import com.listasSimples.Categorias;
import com.listasSimples.listaDoble;
import com.listasSimples.listaEnlazada;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.io.File;
import java.io.IOException;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;


/**
 *
 * @author PERSONAL
 */
public class menu extends javax.swing.JFrame {
    public static listaEnlazada lista = new listaEnlazada();
    public static listaDoble listaD = new listaDoble();
    public static String usuario;
    int xMouse, yMouse;
    
    public menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JPanel();
        lblEdit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCon = new javax.swing.JPanel();
        lblCon = new javax.swing.JLabel();
        btnBiblio = new javax.swing.JPanel();
        lblBiblio = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnMover = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/icons8-image-64.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 90, 50));

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("MENÚ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, 40));

        btnEdit.setBackground(new java.awt.Color(193, 204, 204));

        lblEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEdit.setForeground(new java.awt.Color(51, 51, 51));
        lblEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEdit.setText("Editor");
        lblEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEditMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEditLayout = new javax.swing.GroupLayout(btnEdit);
        btnEdit.setLayout(btnEditLayout);
        btnEditLayout.setHorizontalGroup(
            btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnEditLayout.setVerticalGroup(
            btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEditLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 110, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 150)); // NOI18N
        jLabel5.setText("|");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -20, -1, 250));

        btnCon.setBackground(new java.awt.Color(193, 204, 204));

        lblCon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCon.setForeground(new java.awt.Color(51, 51, 51));
        lblCon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCon.setText("Convertidor");
        lblCon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnConLayout = new javax.swing.GroupLayout(btnCon);
        btnCon.setLayout(btnConLayout);
        btnConLayout.setHorizontalGroup(
            btnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCon, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnConLayout.setVerticalGroup(
            btnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 110, 50));

        btnBiblio.setBackground(new java.awt.Color(193, 204, 204));

        lblBiblio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBiblio.setForeground(new java.awt.Color(51, 51, 51));
        lblBiblio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBiblio.setText("Ingresar a Biblioteca");
        lblBiblio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBiblio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBiblioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBiblioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBiblioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBiblioLayout = new javax.swing.GroupLayout(btnBiblio);
        btnBiblio.setLayout(btnBiblioLayout);
        btnBiblioLayout.setHorizontalGroup(
            btnBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBiblio, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnBiblioLayout.setVerticalGroup(
            btnBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBiblioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnBiblio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 140, 50));

        txtusuario.setBackground(new java.awt.Color(51, 51, 51));
        txtusuario.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(102, 102, 102));
        txtusuario.setText("Ingrese su Usuario");
        txtusuario.setBorder(null);
        txtusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtusuarioMousePressed(evt);
            }
        });
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 120, -1));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("USAC Viewer");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, 40));

        btnMover.setBackground(new java.awt.Color(153, 153, 153));
        btnMover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnMoverMouseDragged(evt);
            }
        });
        btnMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMoverMousePressed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(153, 153, 153));

        lblCerrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(51, 51, 51));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setText("X");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCerrarLayout = new javax.swing.GroupLayout(btnCerrar);
        btnCerrar.setLayout(btnCerrarLayout);
        btnCerrarLayout.setHorizontalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        btnCerrarLayout.setVerticalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btnMoverLayout = new javax.swing.GroupLayout(btnMover);
        btnMover.setLayout(btnMoverLayout);
        btnMoverLayout.setHorizontalGroup(
            btnMoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMoverLayout.createSequentialGroup()
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 512, Short.MAX_VALUE))
        );
        btnMoverLayout.setVerticalGroup(
            btnMoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMoverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 110, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void btnMoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoverMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_btnMoverMousePressed

    private void btnMoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoverMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_btnMoverMouseDragged

    public static void deleteDirectory(Path directory) throws IOException
    {
        if (Files.exists(directory))
        {
            Files.walkFileTree(directory, new SimpleFileVisitor<Path>()
            {
                @Override
                public FileVisitResult visitFile(Path path, BasicFileAttributes attr)
                        throws IOException
                {
                    Files.delete(path);
                    return FileVisitResult.CONTINUE;
                }
 
                @Override
                public FileVisitResult postVisitDirectory(Path path, IOException ex)
                        throws IOException
                {
                    Files.delete(path);
                    return FileVisitResult.CONTINUE;
                }
            });
        }
    }
    
    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        File carpeta = new File("C:\\Users\\PERSONAL\\OneDrive\\Desktop\\IPC1_S12023_Proyecto2_202206560\\Imagen");
        try {
           deleteDirectory(carpeta.toPath());
        } catch (Exception e) {

            e.printStackTrace();
        }
        System.exit(0);

    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseEntered
        btnCerrar.setBackground(Color.red);
        btnCerrar.setForeground(Color.white);
    }//GEN-LAST:event_lblCerrarMouseEntered

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        btnCerrar.setBackground(new Color(153,153,153));
        btnCerrar.setForeground(Color.black);
    }//GEN-LAST:event_lblCerrarMouseExited

    private void lblBiblioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBiblioMouseEntered
        btnBiblio.setBackground(Color.gray);
    }//GEN-LAST:event_lblBiblioMouseEntered

    private void lblBiblioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBiblioMouseExited
        btnBiblio.setBackground(new Color(193,204,204));
    }//GEN-LAST:event_lblBiblioMouseExited

    private void lblConMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConMouseEntered
        btnCon.setBackground(Color.gray);
    }//GEN-LAST:event_lblConMouseEntered

    private void lblConMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConMouseExited
        btnCon.setBackground(new Color(193,204,204));
    }//GEN-LAST:event_lblConMouseExited

    private void lblEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseEntered
        btnEdit.setBackground(Color.gray);
    }//GEN-LAST:event_lblEditMouseEntered

    private void lblEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseExited
        btnEdit.setBackground(new Color(193,204,204));
    }//GEN-LAST:event_lblEditMouseExited

    private void txtusuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusuarioMousePressed
        txtusuario.setText("");
        txtusuario.setForeground(Color.white);
    }//GEN-LAST:event_txtusuarioMousePressed

    private void lblBiblioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBiblioMouseClicked
        chequear();
    }//GEN-LAST:event_lblBiblioMouseClicked

    private void lblEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseClicked
        editor form2 = new editor();
        this.dispose();
        form2.setVisible(true);
    }//GEN-LAST:event_lblEditMouseClicked

    private void lblConMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConMouseClicked
        convertidor form2 = new convertidor();
        this.dispose();
        form2.setVisible(true);
    }//GEN-LAST:event_lblConMouseClicked

    public void chequear(){
        usuario = txtusuario.getText();
        if(lista.existencia(usuario)== false){
            System.out.println(usuario);
            lista.insertar(new Categorias(usuario, "General"));
            Biblioteca form1 = new Biblioteca();
            this.dispose();
            form1.setVisible(true);
        }else{
            Biblioteca form1 = new Biblioteca();
            this.dispose();
            form1.setVisible(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBiblio;
    private javax.swing.JPanel btnCerrar;
    private javax.swing.JPanel btnCon;
    private javax.swing.JPanel btnEdit;
    private javax.swing.JPanel btnMover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBiblio;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblCon;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
